trigger: none
pr: none

resources:
  pipelines:
    - pipeline: appCI
      source: Application-CI
      trigger:
        branches:
          include:
            - main

pool:
  vmImage: ubuntu-latest

stages:

- stage: DEV_DEPLOY
  displayName: Deploy Application to DEV

  jobs:

  - job: DeployDev
    displayName: Deploy Portfolio to DEV Web App

    steps:

    - checkout: self

    - download: appCI
      artifact: portfolio-app

    - task: AzureCLI@2
      displayName: Deploy Application ZIP to DEV
      inputs:
        azureSubscription: 'ado-svc'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Deploying portfolio application to DEV..."

          az webapp deploy \
            --resource-group rg-syed-portfolio-dev \
            --name app-syed-portfolio-dev \
            --src-path "$(Pipeline.Workspace)/appCI/portfolio-app/portfolio-app.zip" \
            --type zip

          echo "DEV deployment completed."

    - script: |
        echo "Validating DEV application..."

        HTTP_STATUS=$(curl -L -s -o /dev/null -w "%{http_code}" \
          https://abid.b18g78.online)

        echo "HTTP Status: $HTTP_STATUS"

        if [ "$HTTP_STATUS" != "200" ]; then
          echo "DEV application health validation failed."
          exit 1
        fi

        echo "DEV application is healthy."
      displayName: Validate DEV Deployment