trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:

# --------------------------------------------------
# 1. Checkout Source Code
# --------------------------------------------------

- checkout: self
  displayName: 'Checkout Source Code'


# --------------------------------------------------
# 2. Display Build Information
# --------------------------------------------------

- script: |
    echo "========================================="
    echo "INFRA-CI Pipeline Started"
    echo "========================================="
    echo "Repository: $(Build.Repository.Name)"
    echo "Branch: $(Build.SourceBranch)"
    echo "Commit: $(Build.SourceVersion)"
    echo "Build ID: $(Build.BuildId)"
  displayName: 'Display Build Information'


# --------------------------------------------------
# 3. Install Terraform
# --------------------------------------------------

- script: |
    set -e

    TERRAFORM_VERSION="1.15.6"

    echo "Installing Terraform ${TERRAFORM_VERSION}..."

    wget -q https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip

    unzip -o terraform_${TERRAFORM_VERSION}_linux_amd64.zip

    sudo mv terraform /usr/local/bin/terraform

    terraform version
  displayName: 'Install Terraform'

# --------------------------------------------------
# 4. Terraform Format Check
# --------------------------------------------------

- script: |
    cd infrastructure/dev
    terraform fmt -check -recursive
  displayName: 'Terraform Format Check'


# --------------------------------------------------
# 5. Terraform Init
# --------------------------------------------------

- script: |
    cd infrastructure/dev
    terraform init
  displayName: 'Terraform Init'


# --------------------------------------------------
# 6. Terraform Validate
# --------------------------------------------------

- script: |
    cd infrastructure/dev
    terraform validate
  displayName: 'Terraform Validate'


# --------------------------------------------------
# 7. Terraform Plan
# --------------------------------------------------
- task: AzureCLI@2
  displayName: 'Terraform Init Validate Plan'
  inputs:
    azureSubscription: 'sc-azure-terraform'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |

      echo "========================================="
      echo "Azure Authentication"
      echo "========================================="

      az account show

      echo ""
      echo "========================================="
      echo "Terraform Init"
      echo "========================================="

      cd infrastructure/dev

      terraform init -backend=false

      echo ""
      echo "========================================="
      echo "Terraform Validate"
      echo "========================================="

      terraform validate

      echo ""
      echo "========================================="
      echo "Terraform Plan"
      echo "========================================="

      terraform plan